// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlGpbNvoe_PKCL2q1arpUXCBrX2coL8sU',
    appId: '1:295812215003:web:c452462879d7d263d35cfe',
    messagingSenderId: '295812215003',
    projectId: 'mero-kagaj-patra-ffd1f',
    authDomain: 'mero-kagaj-patra-ffd1f.firebaseapp.com',
    storageBucket: 'mero-kagaj-patra-ffd1f.appspot.com',
    measurementId: 'G-17QN80QKWL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcW79jmwemss-i8_Fg5_76gJ86SR2Rh-8',
    appId: '1:295812215003:android:65edefc2e57749a2d35cfe',
    messagingSenderId: '295812215003',
    projectId: 'mero-kagaj-patra-ffd1f',
    storageBucket: 'mero-kagaj-patra-ffd1f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXyXYzvvbzuvhFG28_XOvt6RRT511XKyw',
    appId: '1:295812215003:ios:88a9b82e5803d4fbd35cfe',
    messagingSenderId: '295812215003',
    projectId: 'mero-kagaj-patra-ffd1f',
    storageBucket: 'mero-kagaj-patra-ffd1f.appspot.com',
    iosClientId: '295812215003-p897r3fm0ian01frcoamqggld1eh2nv2.apps.googleusercontent.com',
    iosBundleId: 'com.example.meroKagajPatra',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAXyXYzvvbzuvhFG28_XOvt6RRT511XKyw',
    appId: '1:295812215003:ios:88a9b82e5803d4fbd35cfe',
    messagingSenderId: '295812215003',
    projectId: 'mero-kagaj-patra-ffd1f',
    storageBucket: 'mero-kagaj-patra-ffd1f.appspot.com',
    iosClientId: '295812215003-p897r3fm0ian01frcoamqggld1eh2nv2.apps.googleusercontent.com',
    iosBundleId: 'com.example.meroKagajPatra',
  );
}
